# real trader
real_trader_asset_USD: 40000 # [USD] set to 0 to use all assets in the account
real_trader_using_prediction_file_name: "prediction_20250630.csv"
symbols_to_avoid:
 - "ZZZZ" # for example. Add more symbols to avoid if needed.

# kelly fraction calculator
large_scale_close_loop_sim_history_data_folder_name: "prompt1.0.6_gpt-4omini_attempt1_final"
kelly_combine_region_threshold: 2.0 
max_kelly_fraction: 1.0
long_odds_threshold: 0.0
short_odds_threshold: 0.0
usable_region_upper_bound: 12
usable_region_lower_bound: -7.5
