# symbol handler
nasdaq_tickers_file_name: nasdaq_tickers.pkl
nasdaq_financial_report_release_dates_file_name: nasdaq_financial_report_release_dates.csv
market_open_dates_file_name: market_open_dates.csv

stock_exchange_names:
    - nasdaq
    - nyse
    - amex

# LLM model
# openai_handler_class_name: LangChainHandler
openai_handler_class_name: OpenaiHandler
# openai_handler_class_name: OllamaLocalLLMHandler
# openai_model_name: "gpt-4o"
openai_model_name: "gpt-4o-mini"
should_use_cheaper_model: false
openai_weak_model_name: "gpt-4o-mini"
openai_middle_model_name: "o3-mini"
openai_strong_model_name: "gpt-4o"
openai_max_tool_call_loop_amount: 5

# local llm model
local_llm_model: "llama3.2:3b"

# web search rag
web_search_rag_handler_class_name: WebSearchRAG
should_retrieve_full_web_page: true
should_index_web_search_result: false # currently true is not supported
ddg_fetch_news_amount_once: 10
google_search_num_results: 10
url_scrapping_timeout: 60
google_search_max_num_results: 20

# news provider
standard_timeout: 60 # seconds
gpt_long_response_timeout: 300 # seconds
fetch_news_amount_once: 25 # amount of news to fetch at once

# price change prediction
market_trend_prediction_amount: 20 # amount of market trend prediction to fetch
pickup_stock_amount_for_reflection: 3 # amount of stocks to pickup for reflection
prediction_handler_class_name: PriceChangePredictionBeforeFinancialReportHandler

# virtual trader
pick_up_data_from_n_months_ago_before_trade_start_date: 6 # [amount of months] to pick up data from before the trade start date
performance_metrics_pick_up_from_n_days_ago: 180
trade_start_date: "2025-07-03" # start date of the trade
trade_end_date: "2025-07-04" # end date of the trade
historical_data_cutoff_date: "2024-12-31" # cutoff date for historical data used in Kelly fraction and odds calculations
reflect_every_n_days: 29 # reflect every n days
should_update_prompt_in_reflection: false
llm_default_model: "deepseek-chat"
should_clear_temp_data_before_trade: true
trade_mode: "predict_for_future" # either "predict_for_future" or "large_scale_close_loop_sim" or "run_some_symbols_many_times"
close_loop_sim_symbols_file_name: "large_scale_close_loop_sim_symbols.yaml"
should_retrieve_again_all_symbols_for_large_scale_sim: false
max_reflection_amount: 3
max_analysis_amount_per_generation: 5
should_generate_market_trend_summary: false
predict_stock_n_days_ahead: 7
chose_only_n_symbols_for_test: 0 # 0 means infinitive
standalone_update_frequency: 30 # day

# parallel system
num_threads: 8

# ib
should_fetch_earnings_calendar_from_ib_for_all_symbols: true # for prediction, default to false
should_fetch_earnings_calendar_from_ib_for_large_scale_sim: true # for large scale close loop sim, default to true
is_using_real_account: true


# real trader
real_trader_asset_USD: 40000 # [USD] set to 0 to use all assets in the account
real_trader_using_prediction_file_name: "prediction_20250630.csv"

# kelly fraction calculator
large_scale_close_loop_sim_history_data_folder_name: "prompt1.0.6_gpt-4omini_attempt1_final"
kelly_combine_region_threshold: 2.0 
max_kelly_fraction: 1.0
long_odds_threshold: 0.0
short_odds_threshold: 0.0
usable_region_upper_bound: 12
usable_region_lower_bound: -7.5

# prompt version
prompt_version: "1.0.6"

# segment data
segment_chart_period_n_days: 60
should_fetch_segment_data_in_parallel: false
num_thread_for_fetching_segment_data: 4

# proxy
proxy_waiting_time: 10 # seconds
search_waiting_time: 5 # seconds

# standalone analysis
should_run_standalone_analysis_in_parallel: true
num_thread_for_standalone_analysis: 8
n_days_data_fed_to_standalone_analysis: 10

# financial report handler
max_history_financial_report_amount: 1

# volume profile handler
n_days_data_fed_to_volume_profile_handler: 10

# small memory mode
is_small_memory_mode: true
